import Head from "next/head";
import { motion as m } from "framer-motion";
import { container, item } from "../animated";
import Link from "next/link";

export default function Home() {
  return (
    <m.div
      animate={{ y: "0%" }}
      exit={{ opacity: 1 }}
      initial={{ y: "100%" }}
      transition={{ duration: 0.75, ease: "easeOut" }}
      className=" text-gray-900 absolute top-0 left-0 w-full h-full bg-fixed bg-center bg-cover custom-img lg:px-48 px-16 "
    >
      <Head>
        <title>Mark Protsyuk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-white justify-center items-center absolute top-0 left-0 right-0 bottom-0 bg-black/50">
        <div className="mt-56 mb-16 m-4 p-1 font-archivo overflow-hidden ">
          <m.h1
            animate={{ y: 0 }}
            initial={{ y: "100%" }}
            transition={{ delay: 0.5, duration: 0.5 }}
            className="text-5xl text-right lg:text-9xl"
          >
            Mark Protsyuk
          </m.h1>
        </div>
        <div className="flex justify-between">
          <m.div
            variants={container}
            initial="hidden"
            animate="show"
            className="text-left lg:text-2xl text-base m-4"
          >
            <div className="overflow-hidden py-1">
              <m.h3 variants={item}>Front-End Developer</m.h3>
            </div>
            <div className="overflow-hidden py-1">
              <m.h3 variants={item}>NextJS - GraphQL - Tailwind - NodeJS</m.h3>
            </div>
            <div className="overflow-hidden py-1 hover:underline">
              <m.h3 variants={item}>
                <Link
                  target="_blank"
                  rel="noopener noreferrer"
                  href="https://docs.google.com/document/d/e/2PACX-1vTFlRXfRCrGhXAn14GfbD87Lh9eLAoEBJOZNfQw8_fvIFuqPwCbRnD8vDwmUDRO6u_YsBTRkIZIVw08/pub"
                >
                  {"Resume <--"}
                </Link>
              </m.h3>
            </div>
          </m.div>
        </div>
      </main>
    </m.div>
  );
}
