import Head from "next/head";
import { motion as m } from "framer-motion";
import { container, item } from "../animated";
import Link from "next/link";

export default function Home() {
  return (
    <m.div
      animate={{ y: "0%" }}
      exit={{ opacity: 1 }}
      initial={{ y: "100%" }}
      transition={{ duration: 0.75, ease: "easeOut" }}
      className="absolute top-0 left-0 w-full h-full bg-fixed bg-center bg-cover custom-img lg:px-48 px-16 "
    >
      <Head>
        <title>Mark Protsyuk</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.flaticon.com/free-icon/desktop_2933245?term=computer&page=1&position=3&origin=search&related_id=2933245"
        />
      </Head>

      <main className="text-white justify-center items-center absolute top-0 left-0 right-0 bottom-0 bg-black/50">
        <div className="mt-56 xl:mt-64 2xl:mt-72 mb-16 m-4 p-1 overflow-hidden">
          <m.h1
            animate={{ y: 0 }}
            initial={{ y: "100%" }}
            transition={{ delay: 0.5, duration: 0.5 }}
            className="text-center md:text-right text-6xl sm:text-7xl xl:text-9xl text-white"
          >
            Mark Protsyuk
          </m.h1>
        </div>
        <div className="flex justify-center md:justify-between">
          <m.div
            variants={container}
            initial="hidden"
            animate="show"
            className="text-center md:text-left mt-16 md:mt-32 lg:mt-20 lg:text-2xl xl:text-3xl 2xl:text-5xl text-base m-4"
          >
            <div className="overflow-hidden py-1">
              <m.h3 variants={item}>Software Engineer</m.h3>
            </div>
            <div className="overflow-hidden py-1">
              <m.h3 variants={item}>NextJS - GraphQL - Tailwind - NodeJS</m.h3>
            </div>
            <div className="overflow-hidden py-1 underline">
              <m.h3 variants={item}>
                <Link
                  target="_blank"
                  rel="noopener noreferrer"
                  href="https://docs.google.com/document/d/e/2PACX-1vTFlRXfRCrGhXAn14GfbD87Lh9eLAoEBJOZNfQw8_fvIFuqPwCbRnD8vDwmUDRO6u_YsBTRkIZIVw08/pub"
                >
                  {"Resume <--"}
                </Link>
              </m.h3>
            </div>
          </m.div>
        </div>
      </main>
    </m.div>
  );
}
